### ISSUE TITLE
Latest release `xz` dependencies seems to be broken 

### ISSUE THREAD

**Issue by vemonet** [DaniFdezAlvarez/shexer#162] opened 2024-05-14 16:28 UTC
Hi @DaniFdezAlvarez , I am getting this error when installing the latest version 2.5.1 on Ubuntu based distros with python 3.10:

```
Traceback (most recent call last):
  File "/app/wikidata-orthologs-bot/src/wikidata_orthologs_bot/oma.py", line 14, in <module>
    from wikidataintegrator import wdi_core, wdi_helpers, wdi_login
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/wikidataintegrator/__init__.py", line 3, in <module>
    import wikidataintegrator.wdi_core
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/wikidataintegrator/wdi_core.py", line 16, in <module>
    from shexer.shaper import Shaper
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/shexer/shaper.py", line 6, in <module>
    from shexer.utils.factories.class_profiler_factory import get_class_profiler
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/shexer/utils/factories/class_profiler_factory.py", line 1, in <module>
    from shexer.utils.factories.triple_yielders_factory import get_triple_yielder
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/shexer/utils/factories/triple_yielders_factory.py", line 1, in <module>
    from shexer.io.graph.yielder.multi_nt_triples_yielder import MultiNtTriplesYielder
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/shexer/io/graph/yielder/multi_nt_triples_yielder.py", line 1, in <module>
    from shexer.io.graph.yielder.nt_triples_yielder import NtTriplesYielder
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/shexer/io/graph/yielder/nt_triples_yielder.py", line 4, in <module>
    from shexer.io.graph.yielder.base_triples_yielder import BaseTriplesYielder
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/shexer/io/graph/yielder/base_triples_yielder.py", line 6, in <module>
    from shexer.io.line_reader.xz_line_reader import XzFileLineReader
  File "/root/.local/share/hatch/env/virtual/wikidata-ortholog-bot/DyVfgZ7y/wikidata-ortholog-bot/lib/python3.10/site-packages/shexer/io/line_reader/xz_line_reader.py", line 1, in <module>
    from xz import open as xzopen
ModuleNotFoundError: No module named 'xz'
```

No problem with `2.4.1`

Thanks!

**Comment by DaniFdezAlvarez** [comment] 2024-05-14 17:39
Hi @vemonet. Yes, there was a missing line in the setup.py. That should be fixed in release 2.5.2. I'm closing this issue assuming that the problem is indeed fixed, but please, reopen it if that's not the case

**Closed by DaniFdezAlvarez** 2024-05-14 17:39 UTC
